# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

serialize_cookie <- function() {
    .Call('BWPMF_serialize_cookie', PACKAGE = 'BWPMF')
}

deserialize_cookie <- function(src) {
    invisible(.Call('BWPMF_deserialize_cookie', PACKAGE = 'BWPMF', src))
}

serialize_hostname <- function() {
    .Call('BWPMF_serialize_hostname', PACKAGE = 'BWPMF')
}

deserialize_hostname <- function(src) {
    invisible(.Call('BWPMF_deserialize_hostname', PACKAGE = 'BWPMF', src))
}

query_cookie <- function(cookie) {
    .Call('BWPMF_query_cookie', PACKAGE = 'BWPMF', cookie)
}

query_hostname <- function(hostname) {
    .Call('BWPMF_query_hostname', PACKAGE = 'BWPMF', hostname)
}

count_cookie <- function() {
    .Call('BWPMF_count_cookie', PACKAGE = 'BWPMF')
}

count_hostname <- function() {
    .Call('BWPMF_count_hostname', PACKAGE = 'BWPMF')
}

clean_cookie <- function() {
    invisible(.Call('BWPMF_clean_cookie', PACKAGE = 'BWPMF'))
}

clean_hostname <- function() {
    invisible(.Call('BWPMF_clean_hostname', PACKAGE = 'BWPMF'))
}

encode <- function(path, progress = 0) {
    invisible(.Call('BWPMF_encode', PACKAGE = 'BWPMF', path, progress))
}

encode_data <- function(path, progress = 0) {
    .Call('BWPMF_encode_data', PACKAGE = 'BWPMF', path, progress)
}

serialize_history <- function(Rhistory) {
    .Call('BWPMF_serialize_history', PACKAGE = 'BWPMF', Rhistory)
}

deserialize_history <- function(src) {
    .Call('BWPMF_deserialize_history', PACKAGE = 'BWPMF', src)
}

print_history <- function(Rhistory) {
    invisible(.Call('BWPMF_print_history', PACKAGE = 'BWPMF', Rhistory))
}

check_history <- function(Rhistory) {
    .Call('BWPMF_check_history', PACKAGE = 'BWPMF', Rhistory)
}

count_non_zero_of_history <- function(Rhistory) {
    .Call('BWPMF_count_non_zero_of_history', PACKAGE = 'BWPMF', Rhistory)
}

count_cookie_history <- function(Rhistory) {
    .Call('BWPMF_count_cookie_history', PACKAGE = 'BWPMF', Rhistory)
}

count_hostname_history <- function(Rhistory) {
    .Call('BWPMF_count_hostname_history', PACKAGE = 'BWPMF', Rhistory)
}

extract_history <- function(Rhistory, id) {
    .Call('BWPMF_extract_history', PACKAGE = 'BWPMF', Rhistory, id)
}

compute_inverted_index <- function(Rmodel, Rhistory) {
    .Call('BWPMF_compute_inverted_index', PACKAGE = 'BWPMF', Rmodel, Rhistory)
}

init_phi <- function(Rmodel, Rtraining_history) {
    invisible(.Call('BWPMF_init_phi', PACKAGE = 'BWPMF', Rmodel, Rtraining_history))
}

train_once <- function(Rmodel, Rtraining_history, Rtesting_history, Ritem_inverted_index) {
    invisible(.Call('BWPMF_train_once', PACKAGE = 'BWPMF', Rmodel, Rtraining_history, Rtesting_history, Ritem_inverted_index))
}

pmf_logloss <- function(Rmodel, Rhistory) {
    .Call('BWPMF_pmf_logloss', PACKAGE = 'BWPMF', Rmodel, Rhistory)
}

pmf_mae <- function(Rmodel, Rhistory) {
    .Call('BWPMF_pmf_mae', PACKAGE = 'BWPMF', Rmodel, Rhistory)
}

