# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_K <- function(K) {
    invisible(.Call('BWPMF_set_K', PACKAGE = 'BWPMF', K))
}

serialize_cookie <- function(Rpath = NULL) {
    .Call('BWPMF_serialize_cookie', PACKAGE = 'BWPMF', Rpath)
}

deserialize_cookie_raw <- function(src) {
    invisible(.Call('BWPMF_deserialize_cookie_raw', PACKAGE = 'BWPMF', src))
}

deserialize_cookie_path <- function(path) {
    invisible(.Call('BWPMF_deserialize_cookie_path', PACKAGE = 'BWPMF', path))
}

serialize_hostname <- function(Rpath = NULL) {
    .Call('BWPMF_serialize_hostname', PACKAGE = 'BWPMF', Rpath)
}

deserialize_hostname_raw <- function(src) {
    invisible(.Call('BWPMF_deserialize_hostname_raw', PACKAGE = 'BWPMF', src))
}

deserialize_hostname_path <- function(path) {
    invisible(.Call('BWPMF_deserialize_hostname_path', PACKAGE = 'BWPMF', path))
}

query_cookie <- function(cookie) {
    .Call('BWPMF_query_cookie', PACKAGE = 'BWPMF', cookie)
}

query_hostname <- function(hostname) {
    .Call('BWPMF_query_hostname', PACKAGE = 'BWPMF', hostname)
}

count_cookie <- function() {
    .Call('BWPMF_count_cookie', PACKAGE = 'BWPMF')
}

count_hostname <- function() {
    .Call('BWPMF_count_hostname', PACKAGE = 'BWPMF')
}

clean_cookie <- function() {
    invisible(.Call('BWPMF_clean_cookie', PACKAGE = 'BWPMF'))
}

clean_hostname <- function() {
    invisible(.Call('BWPMF_clean_hostname', PACKAGE = 'BWPMF'))
}

encode <- function(path, user_visit_lower_bound = 0L, progress = 0) {
    invisible(.Call('BWPMF_encode', PACKAGE = 'BWPMF', path, user_visit_lower_bound, progress))
}

encode_data <- function(path, progress = 0) {
    .Call('BWPMF_encode_data', PACKAGE = 'BWPMF', path, progress)
}

serialize_history <- function(Rhistory, Rpath = NULL) {
    .Call('BWPMF_serialize_history', PACKAGE = 'BWPMF', Rhistory, Rpath)
}

deserialize_history_raw <- function(src) {
    .Call('BWPMF_deserialize_history_raw', PACKAGE = 'BWPMF', src)
}

deserialize_history_path <- function(path) {
    .Call('BWPMF_deserialize_history_path', PACKAGE = 'BWPMF', path)
}

print_history <- function(Rhistory) {
    invisible(.Call('BWPMF_print_history', PACKAGE = 'BWPMF', Rhistory))
}

check_history <- function(Rhistory) {
    .Call('BWPMF_check_history', PACKAGE = 'BWPMF', Rhistory)
}

count_non_zero_of_history <- function(Rhistory) {
    .Call('BWPMF_count_non_zero_of_history', PACKAGE = 'BWPMF', Rhistory)
}

count_cookie_history <- function(Rhistory) {
    .Call('BWPMF_count_cookie_history', PACKAGE = 'BWPMF', Rhistory)
}

count_hostname_history <- function(Rhistory) {
    .Call('BWPMF_count_hostname_history', PACKAGE = 'BWPMF', Rhistory)
}

extract_history <- function(Rhistory, id) {
    .Call('BWPMF_extract_history', PACKAGE = 'BWPMF', Rhistory, id)
}

test_list_of_list <- function() {
    invisible(.Call('BWPMF_test_list_of_list', PACKAGE = 'BWPMF'))
}

test_phi <- function(Rphi, Rhistory) {
    invisible(.Call('BWPMF_test_phi', PACKAGE = 'BWPMF', Rphi, Rhistory))
}

print_phi_index <- function(Rphi) {
    invisible(.Call('BWPMF_print_phi_index', PACKAGE = 'BWPMF', Rphi))
}

print_history_index <- function(Rhistory) {
    invisible(.Call('BWPMF_print_history_index', PACKAGE = 'BWPMF', Rhistory))
}

init_phi <- function(Rmodel, Rhistory) {
    .Call('BWPMF_init_phi', PACKAGE = 'BWPMF', Rmodel, Rhistory)
}

train_once <- function(Rmodel, Rhistory, Rphi, logger) {
    invisible(.Call('BWPMF_train_once', PACKAGE = 'BWPMF', Rmodel, Rhistory, Rphi, logger))
}

pmf_logloss <- function(Rmodel, Rhistory) {
    .Call('BWPMF_pmf_logloss', PACKAGE = 'BWPMF', Rmodel, Rhistory)
}

